export const PROPERTY_OPTION_DEFAULTS = {
  amenities: ["Parking", "Lift", "Security", "Garden", "Swimming Pool", "Gym", "CCTV", "Power Backup", "Club House", "WiFi", "Air Conditioning", "Water Supply", "Balcony", "Furnished", "Semi Furnished", "Modular Kitchen", "Visitor Parking", "Kids Play Area", "Fire Safety", "Pet Friendly"],
  features: ["Corner Property", "Wide Road Access", "Road Facing", "Vaastu Compliant", "Gated Community", "Prime Location", "High Footfall", "Main Road Touch", "Near Metro", "Near School", "Near Hospital", "Near Market", "New Construction", "Ready Possession", "High ROI"],
  facilities: ["24/7 Water", "Generator Backup", "Society Office", "Waste Management", "Intercom", "Maintenance Staff", "Rainwater Harvesting", "EV Charging", "Service Lift", "Conference Room", "Pantry", "Reception Area"],
  highlights: ["Premium Location", "Verified Listing", "Negotiable Price", "Immediate Possession", "Clear Title", "Loan Approved", "Investor Friendly", "Owner Listed", "Exclusive Mandate"],
  propertyTags: ["ROI", "Pre Leased", "Barter", "Commercial", "Residential", "Office", "Showroom", "Warehouse", "Apartment", "Villa", "Plot", "New Launch", "New Projects", "Hot Deal", "Featured"],
  furnishing: ["Unfurnished", "Semi Furnished", "Fully Furnished", "Bare Shell", "Warm Shell"],
  facing: ["East", "West", "North", "South", "North-East", "North-West", "South-East", "South-West", "Road Facing", "Garden Facing"],
  propertyStatus: ["Ready", "Under Construction", "New Launch", "Resale", "Sold", "Rented"],
  category: ["Residential", "Commercial", "Industrial", "Land/Plot", "Pre-Leased", "Investment", "Retail", "Office", "New Projects"],
  availability: ["Immediate", "Within 15 Days", "Within 30 Days", "Within 3 Months", "After 3 Months", "Under Construction"],
  cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar", "Mumbai"],
  locations: [],
  developers: ["Vaibhavlaxmi Developers", "Lodha Builders", "Reliable India and Corporation", "Haware Properties", "Agastya Infra"],
  projects: ["Gurukrupa Ananatam", "Trump Towers", "Ashapura Skies", "Clinton Heights", "Nathani Heights"],
  propertyTypes: ["Apartments", "Villa", "Bungalow", "Plot", "Office", "Showroom", "Shop", "Warehouse", "Farm House", "Penthouse"],
  dealTypes: ["Sale", "Rent", "Pre-Leased", "Lease", "Resale", "New Launch", "Investment", "ROI"],
  listingStatuses: ["active", "pending", "inactive", "sold", "rented"],
  displayTags: ["Featured", "New", "Hot", "Standard"],
  bhk: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
  measurementUnits: ["sqft", "vigha", "acre", "sq-yard", "sq-meter", "guntha", "hectare", "custom"],
  ownership: ["Freehold", "Leasehold", "Co-operative Society", "Power of Attorney", "Joint Ownership", "Other"],
  floors: ["Ground", "Lower Ground", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "15", "20", "25", "30+"],
  parking: ["No Parking", "Open Parking", "Covered Parking", "1 Car", "2 Cars", "3 Cars", "Visitor Parking", "Basement Parking"],
  constructionStatus: ["Ready to Move", "Under Construction", "New Launch", "OC Received", "Renovated", "Resale"],
  possessionStatus: ["Immediate", "Within 15 Days", "Within 30 Days", "Within 3 Months", "Within 6 Months", "By Agreement"],
  brokerageType: ["Fixed", "Percentage", "One Month Rent", "Half Month Rent", "No Brokerage", "Negotiable"],
  priceUnits: ["Thousand", "Lakh", "Crore", "Per Month", "Per Sqft", "Per Sqyd"],
};

export const PROPERTY_OPTION_GROUPS = Object.keys(PROPERTY_OPTION_DEFAULTS);
