export const ahmedabadAreas = [
  "Properties for sale in Bodakdev",
  "Properties for sale in Thaltej",
  "Properties for sale in Satellite",
  "Properties for sale in Prahlad Nagar",
  "Properties for sale in SG Highway",
  "Properties for sale in Bopal",
  "Properties for sale in South Bopal",
  "Properties for sale in Shela",
  "Properties for sale in Gota",
  "Properties for sale in Chandkheda",
];

export const topListDefaults = [
  { title: "Gurukrupa Ananatam", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 1, city: "", slug: "", description: "" },
  { title: "Trump Towers", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 2, city: "", slug: "", description: "" },
  { title: "Ashapura Skies", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 3, city: "", slug: "", description: "" },
  { title: "Clinton Heights", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 4, city: "", slug: "", description: "" },
  { title: "Nathani Heights", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 5, city: "", slug: "", description: "" },
  { title: "Vaibhavlaxmi Developers", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 1, city: "", slug: "", description: "" },
  { title: "Lodha Builders", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 2, city: "", slug: "", description: "" },
  { title: "Reliable India and Corporation", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 3, city: "", slug: "", description: "" },
  { title: "Haware Properties", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 4, city: "", slug: "", description: "" },
  { title: "Agastya Infra", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 5, city: "", slug: "", description: "" },
];

export const aboutContentDefault = {
  title: "Real Estate with Akshar Estate The Property HUB Confidence.",
  subtitle: "Akshar Estate The Property HUB is a Gujarat-focused brokerage committed to helping clients find the right property with transparency and ease.",
  mainDescription: "We simplify real estate and build lasting relationships through performance. We connect people to the best residential and commercial opportunities.",
  heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=2000",
  ownerName: "Hitesh Patel",
  ownerPhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=1000",
  ownerDesignation: "Founder, Akshar Estate The Property HUB",
  ownerBio: "Hitesh Patel leads Akshar Estate The Property HUB with a practical, client-first approach built around verified opportunities, clear advice, and long-term property value across Gujarat.",
  ownerQuote: "Our goal is simple — to make real estate decisions smarter, faster, and more profitable for our clients.",
  visionTitle: "Our Vision",
  visionContent: "To become a trusted name in real estate by delivering honest guidance and long-term value.",
  missionTitle: "Our Mission",
  missionContent: "Help every buyer, seller, renter, and investor make confident property decisions with verified options, clear advice, and complete support.",
  storyTitle: "Company Story",
  storyContent: "Akshar Estate The Property HUB was built to bring sharper local knowledge, reliable listings, and transparent guidance to Gujarat real estate.",
  stats: [
    { label: "Trust", value: "100%" },
    { label: "Deals Done", value: "500+" },
  ],
  features: [
    { title: "Trusted Guidance", desc: "We prioritize honesty and clear communication in every interaction." },
    { title: "Market Expertise", desc: "Strong understanding of local trends and high-growth opportunities." },
    { title: "Personalized Service", desc: "Every client receives tailored property solutions unique to their needs." },
    { title: "End-to-End Support", desc: "From the initial property search to the final legal deal closure." },
    { title: "Strong Network", desc: "Exclusive access to verified listings and premium off-market properties." },
    { title: "Results Driven", desc: "Our goal is to make decisions smarter, faster, and more profitable." },
  ],
  seoTitle: "About Akshar Estate The Property HUB",
  seoDescription: "Learn about Akshar Estate The Property HUB, our leadership, vision, and Gujarat real estate expertise.",
};

export const contactContentDefault = {
  title: "Let’s discuss your next property move.",
  subtitle: "Share your requirement and our team will help with verified options across Gujarat.",
  phone: "+91 1800-123-4567",
  email: "info@aksharrealestate.com",
  address: "SG Highway, Ahmedabad, Gujarat 380054",
  whatsapp: "+91 98765 43210",
  officeTiming: "Mon - Sat, 10:00 AM to 7:00 PM",
  mapEmbed: "",
  mapLink: "",
  socials: {
    instagram: "",
    facebook: "",
    linkedin: "",
    youtube: "",
  },
  location: {
    address: "SG Highway, Ahmedabad, Gujarat 380054",
    area: "SG Highway",
    city: "Ahmedabad",
    state: "Gujarat",
    pincode: "380054",
    lat: null,
    lng: null,
    placeId: "",
  },
};

export const siteContentDefaults = [
  { key: "siteName", section: "Branding", label: "Site Name", type: "text", value: "Akshar Estate The Property HUB" },
  { key: "heroTitle", section: "Home Hero", label: "Hero Title", type: "textarea", value: "We Turn Spaces into Places You Call Home" },
  { key: "heroSubtitle", section: "Home Hero", label: "Hero Subtitle", type: "textarea", value: "Discover verified homes, apartments, and investment-ready properties across Gujarat." },
  { key: "heroImage", section: "Home Hero", label: "Hero Background Image", type: "text", value: "/house.jpg" },
  { key: "heroCtaText", section: "Home Hero", label: "Hero CTA Text", type: "text", value: "Search" },
  { key: "navbarAreas", section: "Navigation", label: "Navbar Ahmedabad Areas", type: "json", value: ahmedabadAreas },
  { key: "navbarTopLists", section: "Navigation", label: "Top Projects & Developers", type: "json", value: topListDefaults },
  { key: "aboutContent", section: "About Us", label: "About Us CMS Content", type: "json", value: aboutContentDefault },
  { key: "contactContent", section: "Contact Us", label: "Contact Us CMS Content", type: "json", value: contactContentDefault },
  { key: "newEnquiryEmail", section: "Email Templates", label: "New Enquiry Email Template", type: "textarea", value: "Hello {{ userName }}, thanks for enquiring about {{ propertyName }}." },
  { key: "ownerApprovalEmail", section: "Email Templates", label: "Owner Approval Email Template", type: "textarea", value: "Hello {{ ownerName }}, your owner application has been approved." },
];
