export const ahmedabadAreas = [
  "Properties for sale in Bodakdev",
  "Properties for sale in Thaltej",
  "Properties for sale in Satellite",
  "Properties for sale in Prahlad Nagar",
  "Properties for sale in SG Highway",
  "Properties for sale in Bopal",
  "Properties for sale in South Bopal",
  "Properties for sale in Shela",
  "Properties for sale in Gota",
  "Properties for sale in Chandkheda",
];

export const topListDefaults = [
  { title: "Gurukrupa Ananatam", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 1, city: "", slug: "", description: "" },
  { title: "Trump Towers", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 2, city: "", slug: "", description: "" },
  { title: "Ashapura Skies", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 3, city: "", slug: "", description: "" },
  { title: "Clinton Heights", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 4, city: "", slug: "", description: "" },
  { title: "Nathani Heights", type: "project", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 5, city: "", slug: "", description: "" },
  { title: "Vaibhavlaxmi Developers", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 1, city: "", slug: "", description: "" },
  { title: "Lodha Builders", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 2, city: "", slug: "", description: "" },
  { title: "Reliable India and Corporation", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 3, city: "", slug: "", description: "" },
  { title: "Haware Properties", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 4, city: "", slug: "", description: "" },
  { title: "Agastya Infra", type: "developer", enabled: true, featured: true, showInNavbar: true, showInFooter: false, sortOrder: 5, city: "", slug: "", description: "" },
];

export const aboutContentDefault = {
  title: "Real Estate with Akshar Estate The Property HUB Confidence.",
  subtitle: "Akshar Estate The Property HUB is a Gujarat-focused brokerage committed to helping clients find the right property with transparency and ease.",
  mainDescription: "We simplify real estate and build lasting relationships through performance. We connect people to the best residential and commercial opportunities.",
  heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=2000",
  ownerName: "Hitesh Patel",
  ownerPhoto: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=1000",
  ownerDesignation: "Founder, Akshar Estate The Property HUB",
  ownerBio: "Hitesh Patel leads Akshar Estate The Property HUB with a practical, client-first approach built around verified opportunities, clear advice, and long-term property value across Gujarat.",
  ownerQuote: "Our goal is simple — to make real estate decisions smarter, faster, and more profitable for our clients.",
  visionTitle: "Our Vision",
  visionContent: "To become a trusted name in real estate by delivering honest guidance and long-term value.",
  missionTitle: "Our Mission",
  missionContent: "Help every buyer, seller, renter, and investor make confident property decisions with verified options, clear advice, and complete support.",
  storyTitle: "Company Story",
  storyContent: "Akshar Estate The Property HUB was built to bring sharper local knowledge, reliable listings, and transparent guidance to Gujarat real estate.",
  stats: [
    { label: "Trust", value: "100%" },
    { label: "Deals Done", value: "500+" },
  ],
  features: [
    { title: "Trusted Guidance", desc: "We prioritize honesty and clear communication in every interaction." },
    { title: "Market Expertise", desc: "Strong understanding of local trends and high-growth opportunities." },
    { title: "Personalized Service", desc: "Every client receives tailored property solutions unique to their needs." },
    { title: "End-to-End Support", desc: "From the initial property search to the final legal deal closure." },
    { title: "Strong Network", desc: "Exclusive access to verified listings and premium off-market properties." },
    { title: "Results Driven", desc: "Our goal is to make decisions smarter, faster, and more profitable." },
  ],
  seoTitle: "About Akshar Estate The Property HUB",
  seoDescription: "Learn about Akshar Estate The Property HUB, our leadership, vision, and Gujarat real estate expertise.",
};

export const contactContentDefault = {
  title: "Let’s discuss your next property move.",
  subtitle: "Share your requirement and our team will help with verified options across Gujarat.",
  phone: "+91 9998040233",
  secondaryPhone: "",
  email: "aksharestate2006@gmail.com",
  address: "4/1, 4Th Floor, B.K.Complex, Above Kotak Mahindra Bank, Opp, Canara Bank, Gh Road, Sector 16, Gandhinagar : 382016 Gujarat India",
  footerDescription: "Your trusted Gujarat partner for verified Residential, commercial and Industrial spaces, Agriculture Land, Residential Plots, Investment, ROI, Pre Launch, Barter Property and real estate guidance.",
  footerCopyright: "2026 Akshar Estate The Property HUB. All rights reserved.",
  whatsapp: "+91 9998040233",
  whatsappSettings: {
    enabled: true,
    phone: "+91 9998040233",
    message: "Hello Akshar Estate : The Property Hub, I would like to make an enquiry about your property services. Please share more details.",
    position: "bottom-right",
    displayOn: "all",
  },
  officeTiming: "Mon - Sat, 10:00 AM to 7:00 PM",
  mapEmbed: "",
  mapLink: "",
  socials: {
    instagram: "",
    facebook: "",
    linkedin: "",
    youtube: "",
    x: "",
  },
  location: {
    address: "4/1, 4Th Floor, B.K.Complex, Above Kotak Mahindra Bank, Opp, Canara Bank, Gh Road, Sector 16, Gandhinagar : 382016 Gujarat India",
    area: "Sector 16",
    city: "Gandhinagar",
    state: "Gujarat",
    pincode: "382016",
    lat: null,
    lng: null,
    placeId: "",
  },
};

export const homeSectionsContentDefault = {
  videos: {
    eyebrow: "",
    title: "Watch Our Videos",
    subtitle: "Explore our collection of short videos showcasing properties and insights",
    items: [
      { title: "Bungalow for Sale", location: "Karali, Vadodara", image: "/home-video-1.svg", overlay: "LUXURY HOME FOR SALE - VIRTUAL TOUR", button: "", url: "", enabled: true },
      { title: "Bungalow for Sale", location: "Koba, Gandhinagar", image: "/home-video-2.svg", overlay: "", button: "", url: "", enabled: true },
      { title: "Land for Sale", location: "Adajan, Surat", image: "/home-video-3.svg", overlay: "Property Video", button: "", url: "", enabled: true },
      { title: "Villa for Sale", location: "Alkapuri, Vadodara", image: "/home-video-4.svg", overlay: "FOR SALE - DREAM HOME", button: "CONTACT AGENT", url: "", enabled: true },
    ],
  },
  agents: {
    eyebrow: "Our Experts",
    title: "Meet our Expert Agents in Ahmedabad",
    subtitle: "Connect with our certified real estate professionals across India",
    items: [
      { name: "Vikram Patel", city: "Vadodara", image: "/home-agent-1.svg", description: "Experienced real estate professional with extensive knowledge of local market trends and property investment opportunities across India.", linkText: "View Agent Profile", linkUrl: "", enabled: true },
      { name: "Rakesh Dahiyal", city: "Vadodara", image: "/home-agent-2.svg", description: "Experienced real estate professional with extensive knowledge of local market trends and property investment opportunities across India.", linkText: "View Agent Profile", linkUrl: "", enabled: true },
    ],
  },
  testimonials: {
    eyebrow: "Testimonials",
    title: "What Our Clients Say",
    subtitle: "Don't just take our word for it. Here's what our valued clients have to say about their experience with us.",
    items: [
      { name: "Ananya Desai", role: "First-time Buyer", image: "/home-testimonial-1.svg", text: "Buying my first home was daunting, but the Akshar Estate team guided me through every step. They were patient, answered all my questions, and made the entire process stress-free.", rating: 5, enabled: true },
      { name: "Vikram Patel", role: "Commercial Buyer", image: "/home-testimonial-2.svg", text: "Excellent service for commercial properties. They understood our business needs and found us the perfect location. Their professionalism and attention to detail are unmatched.", rating: 5, enabled: true },
      { name: "Priya Sharma", role: "Homeowner", image: "/home-testimonial-3.svg", text: "Akshar Estate made finding my dream home incredibly easy. Their team was professional, responsive, and truly understood what I was looking for.", rating: 5, enabled: true },
      { name: "Rajesh Kumar", role: "Property Investor", image: "/home-testimonial-4.svg", text: "As a real estate investor, I've worked with many agencies. Akshar Estate stands out with their market knowledge and transparent approach.", rating: 5, enabled: true },
      { name: "Amit Shah", role: "Home Buyer", image: "/home-testimonial-5.svg", text: "Smooth and transparent process. The team ensured everything was handled professionally from start to finish.", rating: 5, enabled: true },
      { name: "Sneha Iyer", role: "Investor", image: "/home-testimonial-6.svg", text: "Highly recommend Akshar Estate for property investments. Their insights helped me make the right decisions.", rating: 5, enabled: true },
    ],
  },
  stats: {
    items: [
      { value: "10K+", label: "Happy Clients", enabled: true },
      { value: "15K+", label: "Properties Sold", enabled: true },
      { value: "4.9", label: "Average Rating", enabled: true },
      { value: "25+", label: "Years Experience", enabled: true },
    ],
  },
};

export const siteContentDefaults = [
  { key: "siteName", section: "Branding", label: "Site Name", type: "text", value: "Akshar Estate The Property HUB" },
  { key: "heroTitle", section: "Home Hero", label: "Hero Title", type: "textarea", value: "We Turn Spaces into Places You Call Home" },
  { key: "heroSubtitle", section: "Home Hero", label: "Hero Subtitle", type: "textarea", value: "Discover verified homes, apartments, and investment-ready properties across Gujarat." },
  { key: "heroImage", section: "Home Hero", label: "Hero Background Image", type: "text", value: "/house.jpg" },
  { key: "heroCtaText", section: "Home Hero", label: "Hero CTA Text", type: "text", value: "Search" },
  { key: "homeSectionsContent", section: "Home Sections", label: "Home Sections CMS Content", type: "json", value: homeSectionsContentDefault },
  { key: "navbarAreas", section: "Navigation", label: "Navbar Ahmedabad Areas", type: "json", value: ahmedabadAreas },
  { key: "navbarTopLists", section: "Navigation", label: "Top Projects & Developers", type: "json", value: topListDefaults },
  { key: "aboutContent", section: "About Us", label: "About Us CMS Content", type: "json", value: aboutContentDefault },
  { key: "contactContent", section: "Contact Us", label: "Contact Us CMS Content", type: "json", value: contactContentDefault },
  { key: "newEnquiryEmail", section: "Email Templates", label: "New Enquiry Email Template", type: "textarea", value: "Hello {{ userName }}, thanks for enquiring about {{ propertyName }}." },
  { key: "ownerApprovalEmail", section: "Email Templates", label: "Owner Approval Email Template", type: "textarea", value: "Hello {{ ownerName }}, your owner application has been approved." },
  {
    key: "brokerageSettings",
    section: "Business Settings",
    label: "Brokerage & Commission Settings",
    type: "json",
    value: {
      percentage: 2,
      notes: "Standard brokerage charged on successful property transactions.",
    },
  },
];
